### PR TITLE
Updated to Groovy 4 to support Spring Boot 3

### PR DESCRIPTION
**Pull request by wllianwd**
Migrated to Groovy 4 so it can be used with `Spring Boot 3`:

* Bump version to `3.0.0` as this is a major update
* Updated to use the new `org.apache.groovy`
* Updated Groovy to `4.0.11`
* Updated Spock to `2.3-groovy-4.0`
* Updated GMavenPlus to `2.1.0`

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
@wllianwd can you rebase against `main` so that we see if a CI job hooks in this time?

**Comment by wllianwd** [comment]
> @wllianwd can you rebase against `main` so that we see if a CI job hooks in this time?

done

**Comment by michelzanini** [comment]
Any chance this can be merged? Thanks.

**Comment by Vampire** [comment]
@marcingrzejszczak can you please release a version without this?
The whole point of #29 / #32 was to restore Groovy 2.5 compatibility by compiling with 2.5 again.
But this even increases the version to 4.0 so probably not only broke 2.5, but also 3.0 compatibility. 😭

**Comment by Vampire** [comment]
Yes, confirmed, Groovy 2.5 support is broken again while this release should fix it

**Comment by Vampire** [comment]
Just lowering the compile Groovy version to 2.5 again like in my PR, makes it again compatible with Groovy 2.5, 3.0, and 4.0.
Unfortunately, there is no [MCVE](https://stackoverflow.com/help/mcve) available at all that shows why these changes here were necessary at all to maybe test with it and find an alternative.

**Comment by marcingrzejszczak** [comment]
Sorry for the mess. I've updated the project like this

https://github.com/marcingrzejszczak/spock-subjects-collaborators-extension/commit/4f1da9ce927528f3b1c79929a1edad2d4c6437e2 - 2.0.1 will be Groovy 2.5.x compatible

https://github.com/marcingrzejszczak/spock-subjects-collaborators-extension/commit/b384e14ec67121e9a269809ecd01562ac3140f41 - 2.0.1-groovy-3.0 will be Groovy 3.0.x compatible

**Comment by marcingrzejszczak** [comment]
I have almost 0 time for this project so this is the fastest solution I came up with

**Comment by marcingrzejszczak** [comment]
BTW if you want to take it over @Vampire I don't mind ;)

**Comment by Vampire** [comment]
Thanks, but I already have more on my plate than I should eat. :-D

**Comment by Vampire** [comment]
Did you release those versions already and properly?
The Groovy 3 variant is listed already as version on central.sonatype.com, but both versions are not usable yet.

**Comment by marcingrzejszczak** [comment]
> Thanks, but I already have more on my plate than I should eat. :-D

Don't we all? :D

> Did you release those versions already and properly?

Yeah they are syncing to central, it might take a while

**Comment by marcingrzejszczak** [comment]
Just checked and both are listed in https://repo1.maven.org/maven2/com/blogspot/toomuchcoding/spock-subjects-collaborators-extension/

**Comment by Vampire** [comment]
Yep, now it's there and works, thanks.

**Pull request merged**
