### PR TITLE
Search potential collaborators fields in parent classes

### PR DESCRIPTION
**Pull request by vanta**
Fix for #18

### CODE REVIEW

**Comment by vanta** [comment]
When new version will be released? Can this fix be released as a patch with 1.2.2? Or it must wait for new release 1.3.1?

**Comment by marcingrzejszczak** [comment]
I'm just about to start the release :)

**Comment by marcingrzejszczak** [comment]
There you go! https://github.com/marcingrzejszczak/spock-subjects-collaborators-extension/releases/tag/1.2.2 Now let's wait for this to sync with Central

**Comment by marcingrzejszczak** [comment]
It's there - http://repo2.maven.org/maven2/com/blogspot/toomuchcoding/spock-subjects-collaborators-extension/1.2.2/ - enjoy! And thanks a lot for the PR! :)

**Comment by vanta** [comment]
I've taken it right after you release it, from other repo (JCenter?), but thanks anyway for info.

**Comment by marcingrzejszczak** [comment]
JCenter is also a mirror over Maven Central that's why you could grab it :)

**Comment by vanta** [comment]
My point was that it was there few minutes after release while into Maven Central it took muuuuch longer.

**Comment by marcingrzejszczak** [comment]
Ah I get it :) Anyways I'm happy that you can profit from the new version :D

**Comment by vanta** [comment]
Yeah, it simplified few tests with some big base class a lot :)

**Pull request merged**
